CREATE TABLE CISCOM.TCO_MESSAGE_QUEUE
(
  MESSAGE_ID     VARCHAR2(32 BYTE),
  MESSAGE_TP     VARCHAR2(10 BYTE),
  RECEIVER_ID    VARCHAR2(32 BYTE),
  TITLE          VARCHAR2(100 BYTE),
  MESSAGE        CLOB,
  STATUS         VARCHAR2(2 BYTE)               DEFAULT '00',
  SEND_MAIL_YN   CHAR(1 BYTE)                   DEFAULT 'N',
  SEND_ALRAM_YN  CHAR(1 BYTE)                   DEFAULT 'N',
  SEND_PUSH_YN   CHAR(1 BYTE)                   DEFAULT 'N',
  SEND_SMS_YN    CHAR(1 BYTE)                   DEFAULT 'N',
  REG_DT         CHAR(17 BYTE),
  SEND_DT        CHAR(17 BYTE)
)

CREATE TABLE CMS.TCS_

-- 사용자 ID
-- 시스템 종류(IP 등)
-- 발생 타입

CREATE TABLE CMS.TCS_FAULT_ACTION
(
  ACTION_SEQ     NUMBER(18) CONSTRAINT TCS_FAULT_ACTION_C01 NOT NULL,
  FAULT_SEQ      NUMBER(18) CONSTRAINT TCS_FAULT_ACTION_C02 NOT NULL,
  ACTION_TYPE    VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_ACTION_C03 NOT NULL,
  ACTION_STATUS  VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_ACTION_C04 NOT NULL,
  ACTION_MSG     VARCHAR2(2000 BYTE),
  ACTION_RESULT  VARCHAR2(2000 BYTE),
  ACTION_DT      CHAR(17 BYTE) CONSTRAINT TCS_FAULT_ACTION_C05 NOT NULL,
  REG_DT         CHAR(17 BYTE) CONSTRAINT TCS_FAULT_ACTION_C07 NOT NULL,
  UPD_DT         CHAR(17 BYTE)
)

CREATE TABLE CMS.TCS_FAULT_HISTORY
(
  FAULT_SEQ     NUMBER(18) CONSTRAINT TCS_FAULT_HISTORY_C01 NOT NULL,
  SYSTEM_ID     VARCHAR2(32 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C02 NOT NULL,
  SYSTEM_TP     VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C03 NOT NULL,
  COMPANY_CD    VARCHAR2(32 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C04 NOT NULL,
  FAULT_STATUS  VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C05 NOT NULL,
  FAULT_LEVEL   VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C06 NOT NULL,
  FAULT_TYPE    VARCHAR2(5 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C07 NOT NULL,
  IP_ADDR       VARCHAR2(100 BYTE),
  FAULT_DT      CHAR(17 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C08 NOT NULL,
  RECOVER_DT    CHAR(17 BYTE),
  DURATION_SEC  NUMBER(10),
  REG_DT        CHAR(17 BYTE) CONSTRAINT TCS_FAULT_HISTORY_C10 NOT NULL,
  UPD_DT        CHAR(17 BYTE),
  OCCUR_CNT     NUMBER(5)                       DEFAULT 1
)